### ISSUE TITLE
meross_cloud.sensor could not be set up after update to 0.115

### ISSUE THREAD

**Issue by jdaury** [albertogeniola/meross-homeassistant#137]
After update to 0.115 all power sensors became unavailable. This notification appear on start:

```
The following integrations and platforms could not be set up:

meross_cloud.sensor
Please check your config.
```

Logs:

```
Logger: homeassistant.setup
Source: setup.py:280
First occurred: 9:56:41 PM (1 occurrences)
Last logged: 9:56:41 PM

Unable to prepare setup for platform meross_cloud.sensor: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
```

**Comment by ellite** [comment]
Can confirm this issue. The sockets work fine, climate.* also but sensor.* are unavailable.

**Comment by antro31** [comment]
I also confirm. Unclear if the issue is in this integration or if there is a breaking change in 0.115 that prevents sensors creation.

**Comment by silviudc** [comment]
Having the same issue, the sockets toggle works ok however it seems like it cannot setup the amps/voltage/wattage sensors after 115.0 update

**Comment by silviudc** [comment]
> I also confirm. Unclear if the issue is in this integration or if there is a breaking change in 0.115 that prevents sensors creation.
> I think I get it, there is a change mentioned in the HA (see [here](https://www.home-assistant.io/blog/2020/09/17/release-115#all-changes)):
> 
> * Drop UNIT_ prefix for percentage constant ([@springstan](https://github.com/springstan) - [#39383](https://github.com/home-assistant/core/pull/39383))

Yes replacing the UNIT_ in the sensor.py file fixed the issue for me thanks

**Comment by RedFoxy** [comment]
Same here!

**Comment by blaiser72** [comment]
I also confirm, eliminated the prefix UNIT_ the problem did not reappear

**Comment by swampylee** [comment]
Same issue here. Removing UNIT_ from the sensor.py file worked great.

**Comment by barbatrukko** [comment]
anche per me ha funzionato la rimozione del prefisso UNIT_

**Comment by userMak** [comment]
same here. Can someone give instructions how to remove UNIT_ please?

**Comment by silviudc** [comment]
> same here. Can someone give instructions how to remove UNIT_ please?

You'll need to navigate to your `config\custom_components\meross_cloud` folder, edit the sensor.py file, do a search for `UNIT_` and simply delete that, I think there may be two places to change it in

**Comment by userMak** [comment]
> > same here. Can someone give instructions how to remove UNIT_ please?
> 
> You'll need to navigate to your `config\custom_components\meross_cloud` folder, edit the sensor.py file, do a search for `UNIT_` and simply delete that, I think there may be two places to change it in

That helped, thanks!

**Comment by lukejagger** [comment]
Yes, confirmed UNIT_PERCENTAGE mod to PERCENTAGE works for me also.

**Comment by albertogeniola** [comment]
Thanks guys for the awesome work.
I've just released v1.0.2 which addresses this issue. Can you confirm that's working?

**Comment by ellite** [comment]
Updated and it's working. Thank you for the quick update!
