### ISSUE TITLE
Meross devices no more available in Home Assistant in release 2025.6.1

### ISSUE THREAD

**Issue by piere07** [albertogeniola/meross-homeassistant#557]
**Describe the bug**
Since few days, I can access my Meross devices throught Home Assistant. The integration seems stuck in "Initilisation" phase.

**Your environment**
HomeAssistant version: 2025.6.1 (Core)
Hassio Version (if applicable): 15.2
Hardware environment: Raspberry PI 4 - 4 GB RAM

**Logs taken when the issue happened**
```
See attached log file.
[home-assistant_meross_cloud_2025-06-15T06-32-44.128Z_modif.log](https://github.com/user-attachments/files/20744343/home-assistant_meross_cloud_2025-06-15T06-32-44.128Z_modif.log)

```

**Comment by joanluk** [comment]
I have the same problem. With HA 2025.5.x it´s works. After upgrade to 2025.6.1, seems stuck in "Initilisation" phase.

**Comment by pedromrg** [comment]
https://github.com/albertogeniola/meross-homeassistant/issues/554#issuecomment-2964379526

fixed.

**Comment by piere07** [comment]
After applying the patch proposed by Alberto, the issue has gone.
Many thanks for your so good job.
Best regards, Pierre.

**Comment by thibaud-sanchez** [comment]
I still have issue here with latest version:
```

2025-06-17 08:28:01.720 ERROR (MainThread) [custom_components.meross_cloud] Error occurred.
-------------------------------------
Component version: 0.4.8.0
Device info: 
<Unavailable>
Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 427, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(config_entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-06-17 08:28:02.093 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'meross_cloud' sets option flow config_entry explicitly, which is deprecated at custom_components/meross_cloud/config_flow.py, line 404: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/albertogeniola/meross-homeassistant

```

**Comment by inf1783** [comment]
> I still have issue here with latest version:
> 
> ```
> 
> 2025-06-17 08:28:01.720 ERROR (MainThread) [custom_components.meross_cloud] Error occurred.
> -------------------------------------
> Component version: 0.4.8.0
> Device info: 
> <Unavailable>
> Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
> Traceback (most recent call last):
>   File "/config/custom_components/meross_cloud/__init__.py", line 427, in async_setup_entry
>     hass.config_entries.async_forward_entry_setup(config_entry, platform)
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
> 2025-06-17 08:28:02.093 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'meross_cloud' sets option flow config_entry explicitly, which is deprecated at custom_components/meross_cloud/config_flow.py, line 404: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/albertogeniola/meross-homeassistant
> ```

Same for me

**Comment by d4icon** [comment]
Same problem

**Comment by gcadoret** [comment]
hello 
same

Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.meross_cloud
Source: custom_components/meross_cloud/__init__.py:427
intégration: Meross Cloud IoT
S'est produit pour la première fois: 09:15:48 (5 occurrences)
Dernier enregistrement: 09:17:24

Error occurred. ------------------------------------- Component version: 0.4.9.0 Device info: <Unavailable> Error Message: "An exception occurred while setting up the meross manager. Setup will be retried..."
Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/__init__.py", line 427, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(config_entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by albertogeniola** [comment]
Duplicate of #554.

Please update to v1.3.7 and you should be good to go!
